#!/Users/Arief/Desktop/Nexus/nexus_python_env/bin/python
"""
OAuth 2.0 Server - Auto-generated by Frenly Real API Engine
"""

import os
from authlib.integrations.starlette_client import OAuth
from authlib.oauth2.rfc6749.grants import ResourceOwnerPasswordCredentialsGrant
from dotenv import load_dotenv
from jose import jwt
from datetime import datetime, timedelta
from typing import Optional

from database.models import User
from database.config import get_db
from auth.jwt_auth import verify_password

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
ALGORITHM = "HS256"

# OAuth client for external providers
oauth = OAuth()

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None):
    """Create JWT access token"""
    to_encode = data.copy()
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=15)
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt


oauth.register(
    name='github',
    client_id=os.getenv('GITHUB_CLIENT_ID'),
    client_secret=os.getenv('GITHUB_CLIENT_SECRET'),
    access_token_url='https://github.com/login/oauth/access_token',
    authorize_url='https://github.com/login/oauth/authorize',
    api_base_url='https://api.github.com/',
    client_kwargs={'scope': 'user:email'}
)