global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'nexus-app'
    static_configs:
      - targets: ['nexus-app-opt:9090']
    scrape_interval: 10s
    metrics_path: /metrics
