#!/Users/Arief/Desktop/Nexus/nexus_python_env/bin/python
"""
🛣️ API Routers - Auto-generated by Frenly Real API Engine
"""

import logging
from fastapi import APIRouter, Depends, HTTPException, status
from typing import List, Optional, Any, Dict
from sqlalchemy.orm import Session
from fastapi.security import OAuth2PasswordRequestForm
from pydantic import BaseModel, Field

from database.config import get_db
from database.models import User, Workflow
from auth.jwt_auth import get_current_user, verify_password, create_access_token, get_password_hash
from models import UserCreate, UserUpdate, User as UserModel, WorkflowCreate, WorkflowUpdate, Workflow as WorkflowModel

logger = logging.getLogger(__name__)

# Main API router
api_router = APIRouter()

# Auth router
auth_router = APIRouter(prefix="/auth", tags=["Authentication"])

@auth_router.post("/register", response_model=UserModel)
async def register(user: UserCreate, db: Session = Depends(get_db)):
    """User registration endpoint"""
    logger.info(f"Attempting to register user: {user.email}")
    db_user = db.query(User).filter(User.email == user.email).first()
    if db_user:
        logger.warning(f"Registration failed: Email already registered: {user.email}")
        raise HTTPException(status_code=400, detail="Email already registered")
    hashed_password = get_password_hash(user.password)
    db_user = User(email=user.email, password_hash=hashed_password)
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    logger.info(f"User registered successfully: {db_user.email}")
    return db_user

@auth_router.post("/login", response_model=dict)
async def login(form_data: OAuth2PasswordRequestForm = Depends(), db: Session = Depends(get_db)):
    """User login endpoint"""
    logger.info(f"Attempting to log in user: {form_data.username}")
    user = db.query(User).filter(User.email == form_data.username).first()
    if not user or not verify_password(form_data.password, user.password_hash):
        logger.warning(f"Login failed: Incorrect email or password for user: {form_data.username}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect email or password",
            headers={"WWW-Authenticate": "Bearer"},
        )
    access_token = create_access_token(data={"sub": user.email})
    logger.info(f"User logged in successfully: {user.email}")
    return {"access_token": access_token, "token_type": "bearer"}

@auth_router.post("/refresh", response_model=dict)
async def refresh_token(current_user: User = Depends(get_current_user)):
    """Token refresh endpoint"""
    logger.info(f"Token refresh requested for user: {current_user.email}")
    new_access_token = create_access_token(data={"sub": current_user.email})
    logger.info(f"New access token generated for user: {current_user.email}")
    return {"access_token": new_access_token, "token_type": "bearer"}

# Users router
users_router = APIRouter(prefix="/users", tags=["Users"])

@users_router.get("/me", response_model=UserModel)
async def get_current_user_info(current_user: User = Depends(get_current_user)):
    """Get current user information"""
    logger.info(f"Fetching current user info for: {current_user.email}")
    return current_user

# Workflows router
workflows_router = APIRouter(prefix="/workflows", tags=["Workflows"])

@workflows_router.get("/", response_model=List[WorkflowModel])
async def list_workflows(
    skip: int = 0,
    limit: int = 100,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """List all workflows"""
    logger.info(f"Listing workflows for user: {current_user.email}, skip: {skip}, limit: {limit}")
    workflows = db.query(Workflow).filter(Workflow.owner_id == current_user.id).offset(skip).limit(limit).all()
    logger.info(f"Found {len(workflows)} workflows for user: {current_user.email}")
    return workflows

@workflows_router.post("/", response_model=WorkflowModel)
async def create_workflow(
    workflow: WorkflowCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Create new workflow"""
    logger.info(f"User {current_user.email} attempting to create workflow: {workflow.name}")
    db_workflow = db.query(Workflow).filter(Workflow.owner_id == current_user.id).first()
    if db_workflow:
        logger.warning(f"Workflow creation failed: Workflow with name {workflow.name} already exists for user {current_user.email}")
        raise HTTPException(status_code=400, detail="Workflow with this name already exists")
    db_workflow = Workflow(**workflow.dict(), owner_id=current_user.id)
    db.add(db_workflow)
    db.commit()
    db.refresh(db_workflow)
    logger.info(f"Workflow created successfully: {db_workflow.name} by {current_user.email}")
    return db_workflow

@workflows_router.get("/{workflow_id}", response_model=WorkflowModel)
async def get_workflow(
    workflow_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    logger.info(f"User {current_user.email} requesting workflow: {workflow_id}")
    db_workflow = db.query(Workflow).filter(Workflow.id == workflow_id, Workflow.owner_id == current_user.id).first()
    if db_workflow is None:
        logger.warning(f"Workflow not found: {workflow_id} for user: {current_user.email}")
        raise HTTPException(status_code=404, detail="Workflow not found")
    logger.info(f"Workflow {workflow_id} retrieved successfully by {current_user.email}")
    return db_workflow

@workflows_router.put("/{workflow_id}", response_model=WorkflowModel)
async def update_workflow(
    workflow_id: str,
    workflow: WorkflowUpdate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Update workflow"""
    logger.info(f"User {current_user.email} attempting to update workflow: {workflow_id}")
    db_workflow = db.query(Workflow).filter(Workflow.id == workflow_id, Workflow.owner_id == current_user.id).first()
    if db_workflow is None:
        logger.warning(f"Workflow update failed: Workflow not found: {workflow_id} for user: {current_user.email}")
        raise HTTPException(status_code=404, detail="Workflow not found")
    
    update_data = workflow.dict(exclude_unset=True)
    for key, value in update_data.items():
        setattr(db_workflow, key, value)
        
    db.commit()
    db.refresh(db_workflow)
    logger.info(f"Workflow {workflow_id} updated successfully by {current_user.email}")
    return db_workflow

@workflows_router.delete("/{workflow_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_workflow(
    workflow_id: str,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Delete workflow"""
    logger.info(f"User {current_user.email} attempting to delete workflow: {workflow_id}")
    db_workflow = db.query(Workflow).filter(Workflow.id == workflow_id, Workflow.owner_id == current_user.id).first()
    if db_workflow is None:
        logger.warning(f"Workflow deletion failed: Workflow not found: {workflow_id} for user: {current_user.email}")
        raise HTTPException(status_code=404, detail="Workflow not found")
    db.delete(db_workflow)
    db.commit()
    logger.info(f"Workflow {workflow_id} deleted successfully by {current_user.email}")
    return 

# AI router
ai_router = APIRouter(prefix="/ai", tags=["AI"])

class PredictionRequest(BaseModel):
    model_id: str = Field(..., description="Model identifier, e.g., 'fraud_detection_v1'")
    items: List[Dict[str, Any]] = Field(..., description="List of records to score")

class PredictionResult(BaseModel):
    model_id: str
    predictions: List[Dict[str, Any]]

@ai_router.get("/models", response_model=List[Dict[str, Any]])
async def list_models(current_user: User = Depends(get_current_user)):
    """List available AI models"""
    models = [
        {"id": "fraud_detection_v1", "name": "Fraud Detection Model v1", "type": "classification"}
    ]
    logger.info(f"Listing AI models for user: {current_user.email} -> {len(models)} models")
    return models

@ai_router.post("/predict", response_model=PredictionResult)
async def predict(request: PredictionRequest, current_user: User = Depends(get_current_user)):
    predictions: List[Dict[str, Any]] = []
    for idx, item in enumerate(request.items):

# Include all routers
api_router.include_router(auth_router)
api_router.include_router(users_router)
api_router.include_router(workflows_router)
api_router.include_router(ai_router)
