#!/usr/bin/env python3
"""
🗜️ Compression Manager
Handles Gzip, Brotli, and other compression formats for frontend assets
"""

import os
import gzip
import brotli
import zlib
import argparse
from pathlib import Path
from typing import Dict, List, Optional, Tuple
import mimetypes
import time

class CompressionManager:
    """Advanced compression manager for web assets"""
    
    def __init__(self):
        self.compression_formats = {
            'gzip': self._compress_gzip,
            'brotli': self._compress_brotli,
            'deflate': self._compress_deflate
        }
        self.mime_types = {
            '.html': 'text/html',
            '.css': 'text/css',
            '.js': 'application/javascript',
            '.json': 'application/json',
            '.xml': 'application/xml',
            '.svg': 'image/svg+xml',
            '.txt': 'text/plain'
        }
    
    def compress_file(self, input_path: str, output_path: str = None, 
                     compression_type: str = 'gzip', quality: int = 6) -> Dict:
        """Compress a single file"""
        input_file = Path(input_path)
        
        if not input_file.exists():
            raise FileNotFoundError(f"Input file not found: {input_path}")
        
        # Determine output path
        if not output_path:
            suffix = f'.{compression_type}' if compression_type != 'gzip' else '.gz'
            output_path = str(input_file.with_suffix(input_file.suffix + suffix))
        
        # Read input file
        with open(input_file, 'rb') as f:
            data = f.read()
        
        # Compress
        if compression_type not in self.compression_formats:
            raise ValueError(f"Unsupported compression type: {compression_type}")
        
        compressed_data = self.compression_formats[compression_type](data, quality)
        
        # Write compressed file
        with open(output_path, 'wb') as f:
            f.write(compressed_data)
        
        # Calculate compression ratio
        original_size = len(data)
        compressed_size = len(compressed_data)
        ratio = (1 - compressed_size / original_size) * 100
        
        return {
            'input_file': input_path,
            'output_file': output_path,
            'compression_type': compression_type,
            'original_size': original_size,
            'compressed_size': compressed_size,
            'compression_ratio': ratio,
            'mime_type': self._get_mime_type(input_file.suffix)
        }
    
    def compress_directory(self, input_dir: str, output_dir: str = None,
                          compression_type: str = 'gzip', quality: int = 6,
                          recursive: bool = True) -> List[Dict]:
        """Compress all files in a directory"""
        input_path = Path(input_dir)
        
        if not input_path.exists():
            raise FileNotFoundError(f"Input directory not found: {input_dir}")
        
        # Set output directory
        if not output_dir:
            output_dir = str(input_path / 'compressed')
        
        output_path = Path(output_dir)
        output_path.mkdir(exist_ok=True)
        
        results = []
        
        # Find files to compress
        pattern = '**/*' if recursive else '*'
        for file_path in input_path.glob(pattern):
            if file_path.is_file() and self._should_compress(file_path):
                try:
                    relative_path = file_path.relative_to(input_path)
                    output_file = output_path / relative_path
                    output_file.parent.mkdir(parents=True, exist_ok=True)
                    
                    result = self.compress_file(str(file_path), str(output_file), 
                                              compression_type, quality)
                    results.append(result)
                    
                except Exception as e:
                    print(f"Error compressing {file_path}: {e}")
        
        return results
    
    def create_nginx_config(self, compressed_dir: str, output_file: str = None) -> str:
        """Create Nginx configuration for serving compressed files"""
        if not output_file:
            output_file = 'nginx_compression.conf'
        
        config = """# Nginx Compression Configuration
# Generated by Compression Manager

# Enable gzip compression
gzip on;
gzip_vary on;
gzip_min_length 1024;
gzip_proxied any;
gzip_comp_level 6;
gzip_types
    text/plain
    text/css
    text/xml
    text/javascript
    application/json
    application/javascript
    application/xml+rss
    application/atom+xml
    image/svg+xml;

# Enable Brotli compression (if module available)
# brotli on;
# brotli_comp_level 6;
# brotli_types
#     text/plain
#     text/css
#     application/json
#     application/javascript
#     text/xml
#     application/xml
#     application/xml+rss
#     text/javascript;

# Serve pre-compressed files
location ~* \\.(css|js|html|json|xml|svg|txt)$ {
    # Try to serve pre-compressed version first
    location ~* \\.(css|js|html|json|xml|svg|txt)\\.br$ {
        add_header Content-Encoding br;
        add_header Vary "Accept-Encoding";
    }
    
    location ~* \\.(css|js|html|json|xml|svg|txt)\\.gz$ {
        add_header Content-Encoding gzip;
        add_header Vary "Accept-Encoding";
    }
    
    # Fallback to original file
    try_files $uri$suffix $uri =404;
}
"""
        
        with open(output_file, 'w') as f:
            f.write(config)
        
        return config
    
    def _compress_gzip(self, data: bytes, quality: int = 6) -> bytes:
        """Compress data using gzip"""
        return gzip.compress(data, compresslevel=quality)
    
    def _compress_brotli(self, data: bytes, quality: int = 6) -> bytes:
        """Compress data using Brotli"""
        try:
            return brotli.compress(data, quality=quality)
        except Exception:
            # Fallback to gzip if Brotli not available
            return gzip.compress(data, compresslevel=quality)
    
    def _compress_deflate(self, data: bytes, quality: int = 6) -> bytes:
        """Compress data using deflate"""
        level = max(1, min(9, quality))
        return zlib.compress(data, level)
    
    def _should_compress(self, file_path: Path) -> bool:
        """Determine if file should be compressed"""
        # Only compress text-based files
        compressible_extensions = {'.html', '.css', '.js', '.json', '.xml', '.svg', '.txt'}
        return file_path.suffix.lower() in compressible_extensions
    
    def _get_mime_type(self, suffix: str) -> str:
        """Get MIME type for file extension"""
        return self.mime_types.get(suffix, 'application/octet-stream')

class AssetOptimizer:
    """Asset optimization manager"""
    
    def __init__(self):
        self.compression_manager = CompressionManager()
    
    def optimize_assets(self, input_dir: str, output_dir: str = None) -> Dict:
        """Optimize all assets in directory"""
        start_time = time.time()
        
        if not output_dir:
            output_dir = str(Path(input_dir) / 'optimized')
        
        results = {
            'input_directory': input_dir,
            'output_directory': output_dir,
            'compression_results': [],
            'total_files': 0,
            'total_original_size': 0,
            'total_compressed_size': 0,
            'total_savings': 0,
            'processing_time': 0
        }
        
        # Compress with different formats
        for compression_type in ['gzip', 'brotli']:
            try:
                compression_results = self.compression_manager.compress_directory(
                    input_dir, f"{output_dir}_{compression_type}", 
                    compression_type, quality=6
                )
                results['compression_results'].extend(compression_results)
                
                for result in compression_results:
                    results['total_files'] += 1
                    results['total_original_size'] += result['original_size']
                    results['total_compressed_size'] += result['compressed_size']
                    
            except Exception as e:
                print(f"Error with {compression_type} compression: {e}")
        
        # Calculate totals
        results['total_savings'] = results['total_original_size'] - results['total_compressed_size']
        results['processing_time'] = time.time() - start_time
        
        # Create Nginx config
        nginx_config = self.compression_manager.create_nginx_config(output_dir)
        
        # Save results
        results_file = Path(output_dir) / 'optimization_results.json'
        import json
        with open(results_file, 'w') as f:
            json.dump(results, f, indent=2)
        
        return results

def main():
    parser = argparse.ArgumentParser(description='Compression Manager')
    parser.add_argument('input', help='Input file or directory')
    parser.add_argument('-o', '--output', help='Output file or directory')
    parser.add_argument('-t', '--type', choices=['gzip', 'brotli', 'deflate'], 
                       default='gzip', help='Compression type')
    parser.add_argument('-q', '--quality', type=int, default=6, 
                       help='Compression quality (1-9)')
    parser.add_argument('--recursive', action='store_true', 
                       help='Process directories recursively')
    parser.add_argument('--optimize', action='store_true', 
                       help='Full asset optimization')
    parser.add_argument('--nginx-config', action='store_true', 
                       help='Generate Nginx configuration')
    
    args = parser.parse_args()
    
    compression_manager = CompressionManager()
    
    if args.optimize:
        optimizer = AssetOptimizer()
        results = optimizer.optimize_assets(args.input, args.output)
        print(f"Optimization complete:")
        print(f"  Files processed: {results['total_files']}")
        print(f"  Original size: {results['total_original_size']:,} bytes")
        print(f"  Compressed size: {results['total_compressed_size']:,} bytes")
        print(f"  Total savings: {results['total_savings']:,} bytes")
        print(f"  Processing time: {results['processing_time']:.2f}s")
        
        if args.nginx_config:
            nginx_config = compression_manager.create_nginx_config(args.output or args.input)
            print(f"Nginx configuration saved to: nginx_compression.conf")
    
    else:
        input_path = Path(args.input)
        
        if input_path.is_file():
            result = compression_manager.compress_file(
                args.input, args.output, args.type, args.quality
            )
            print(f"Compressed: {result['input_file']} -> {result['output_file']}")
            print(f"  Compression ratio: {result['compression_ratio']:.1f}%")
            print(f"  Original size: {result['original_size']:,} bytes")
            print(f"  Compressed size: {result['compressed_size']:,} bytes")
            
        elif input_path.is_dir():
            results = compression_manager.compress_directory(
                args.input, args.output, args.type, args.quality, args.recursive
            )
            print(f"Compressed {len(results)} files")
            total_original = sum(r['original_size'] for r in results)
            total_compressed = sum(r['compressed_size'] for r in results)
            total_savings = total_original - total_compressed
            print(f"  Total savings: {total_savings:,} bytes ({total_savings/total_original*100:.1f}%)")

if __name__ == '__main__':
    main()
