#!/Users/Arief/Desktop/Nexus/nexus_python_env/bin/python
"""
🗄️ Database Configuration - Auto-generated by Frenly Real API Engine
"""

import os
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from dotenv import load_dotenv

load_dotenv()

# Database configuration with proper Docker service name
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nexus_user:nexus_password@postgres:5432/nexus_platform"
)

# Create engine with connection pooling
engine = create_engine(
    DATABASE_URL,
    pool_pre_ping=True,
    pool_recycle=300,
    echo=False
)

# Create session factory
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

# Base class for models
Base = declarative_base()

def get_db():
    """Get database session"""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

async def init_db():
    """Initialize database with proper error handling"""
    try:
        
        # Import models to ensure they are registered
        from .models import User, Workflow
        
        # Create all tables
        Base.metadata.create_all(bind=engine)
        print("✅ Database initialized successfully")
    except Exception as e:
        print(f"❌ Database initialization failed: {e}")
        raise
